# Generated by Django 5.2.15 on 2026-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('district', models.CharField(default='Chennai', max_length=50)),
                ('college_type', models.CharField(choices=[('govt', 'Government'), ('private', 'Private'), ('deemed', 'Deemed')], default='private', max_length=10)),
                ('streams_offered', models.CharField(default='science', max_length=200)),
                ('cutoff_oc', models.FloatField(default=0)),
                ('cutoff_bc', models.FloatField(default=0)),
                ('cutoff_mbc', models.FloatField(default=0)),
                ('cutoff_sc', models.FloatField(default=0)),
                ('fees_per_year', models.IntegerField(default=0)),
                ('hostel_available', models.BooleanField(default=False)),
                ('scholarship_available', models.BooleanField(default=False)),
                ('naac_grade', models.CharField(blank=True, max_length=5)),
                ('website', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
