# Generated by Django 5.2.15 on 2026-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('community', models.CharField(choices=[('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST'), ('OC', 'OC'), ('all', 'All Communities')], default='all', max_length=10)),
                ('stream', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('all', 'All Streams')], default='all', max_length=20)),
                ('income_limit', models.IntegerField(default=250000)),
                ('deadline', models.DateField()),
                ('apply_link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('documents_required', models.TextField(blank=True)),
            ],
        ),
    ]
