# Generated by Django 5.2.15 on 2026-06-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='description_tamil',
            field=models.TextField(blank=True),
        ),
    ]
