# Generated by Django 5.2.15 on 2026-06-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('stream', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('all', 'All')], default='science', max_length=20)),
                ('state', models.CharField(default='National', max_length=50)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('exam_date', models.DateField()),
                ('result_date', models.DateField(blank=True, null=True)),
                ('official_link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('eligibility_level', models.CharField(choices=[('12th', 'After 12th'), ('ug', 'Undergraduate Completed'), ('all', 'All Students')], default='12th', max_length=20)),
            ],
        ),
    ]
